apiVersion: v1
kind: Pod
metadata:
  name: api-gateway-test-pod
spec:
  containers:
    - name: api-gateway-container
      image: openjdk:16
      ports:
        - containerPort: 7777
      
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-test-service
spec:
  selector:
    app: api-gateway-pod 
  ports:
    - protocol: TCP
      port: 77
      targetPort: 7777